sudo: required
language: c++ 

addons: 
  apt:
    sources: 
    - ubuntu-toolchain-r-test
    packages: 
    - gcc-6
    - g++-6

script: 
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-6 /usr/bin/gcc
  - gcc --version
  - cmake .
  - cmake --build . -- -j2